# Generated by Django 2.2.7 on 2019-12-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('X', models.FloatField(help_text='X', null=True)),
                ('Y', models.FloatField(help_text='Y', null=True)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=15, primary_key=True, serialize=False)),
                ('Hectare', models.CharField(help_text='Hectare', max_length=4, null=True)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=2, null=True)),
                ('Date', models.DateField(help_text='Date', null=True)),
                ('S_number', models.CharField(help_text='Hectare Squirrel Number', max_length=10, null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', 'Unknown'), ('', '')], default='', help_text='Age', max_length=12, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon'), ('', '')], default='', help_text='Primary Fur Color', max_length=10, null=True)),
                ('Loc', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('', '')], default='', help_text='Location', max_length=20, null=True)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific Location', max_length=100, null=True)),
                ('Running', models.BooleanField(null=True)),
                ('Chasing', models.BooleanField(null=True)),
                ('Climbing', models.BooleanField(null=True)),
                ('Eating', models.BooleanField(null=True)),
                ('Foraging', models.BooleanField(null=True)),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=200, null=True)),
                ('Kuks', models.BooleanField(null=True)),
                ('Quaas', models.BooleanField(null=True)),
                ('Moans', models.BooleanField(null=True)),
                ('Tail_flags', models.BooleanField(null=True)),
                ('Tail_twitches', models.BooleanField(null=True)),
                ('Approaches', models.BooleanField(null=True)),
            ],
        ),
    ]
