# Generated by Django 2.2.7 on 2019-12-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
