# Generated by Django 2.2.7 on 2019-12-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191209_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(decimal_places=40, help_text='Longitude', max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(decimal_places=40, help_text='latitude', max_digits=50, null=True),
        ),
    ]
