# Generated by Django 2.2.7 on 2019-12-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191209_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Hectare',
            field=models.CharField(default=None, help_text='Hectare', max_length=4, null=True),
        ),
    ]
