# Generated by Django 2.2.7 on 2019-12-09 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20191209_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='S_number',
        ),
    ]
