# Generated by Django 2.2.7 on 2019-12-09 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0005_auto_20191209_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='X',
            field=models.DecimalField(decimal_places=15, help_text='Longitude', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Y',
            field=models.DecimalField(decimal_places=15, help_text='Latitude', max_digits=20, null=True),
        ),
    ]
